### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by mnmateus** [fifonik/ElegooNeptuneThumbnailPrusaMod#14]
Hi. I'm having this issue with your thumbnail generator. Already tried running from phyton without success. 
I'm using Orca Slicer 2.2.0. 

2024-09-05 11:43:01,942 - INFO - Input file: C:\Users\Mateus\AppData\Local\Temp\.OrcaSlicer.upload.ac28-0ae8-eba3-1e42
2024-09-05 11:43:01,943 - INFO - The first thumbnail from input file larger than 100x100 will be used
2024-09-05 11:43:02,055 - ERROR - Error occurred while running application.
Traceback (most recent call last):
  File "J:\work\programming\Python\ElegooNeptuneThumbnailPrusaMod\ElegooNeptuneThumbnailPrusaMod\thumbnail.py", line 556, in <module>
  File "J:\work\programming\Python\ElegooNeptuneThumbnailPrusaMod\ElegooNeptuneThumbnailPrusaMod\thumbnail.py", line 432, in run
  File "J:\work\programming\Python\ElegooNeptuneThumbnailPrusaMod\ElegooNeptuneThumbnailPrusaMod\thumbnail.py", line 204, in prepare
  File "J:\work\programming\Python\ElegooNeptuneThumbnailPrusaMod\ElegooNeptuneThumbnailPrusaMod\thumbnail.py", line 35, in myround
ValueError: could not convert string to float: '28219.52, 0.00'

**Comment by fifonik** [comment]
Sorry, email notifications for the repository were turned off :(

For me it looks like there is something strange in line with:
`filament used [mm] =`
My script expecting the value to be numeric, but in ur case it is **28219.52, 0.00**
It is possible that this is related to multi-filament or multi-extruder configuration that I know nothing about at this time.
It would be nice if you can re-produce the issue and show the line that causing the issue (find it in gcode by the number from error message).
I will try to investigate and provide feedback and fix (if possible).

**Comment by Felix14-v2** [comment]
> It is possible that this is related to multi-filament or multi-extruder configuration

Can confirm, as soon as I add more than one filament to my settings (you can add it even to a single-extruder setup), the script will break:
```
2025-01-24 16:48:54,783 - INFO - Input file: C:\Users\9D68~1\AppData\Local\Temp/orcaslicer_model/Fri_Jan_24/16_32_56#15788#40/Metadata\.15788.0.gcode.pp
2025-01-24 16:48:54,783 - INFO - The first thumbnail from input file larger than 100x100 will be used
2025-01-24 16:48:54,804 - ERROR - Error occurred while running application.
Traceback (most recent call last):
  File "J:\work\programming\Python\ElegooNeptuneThumbnailPrusaMod\ElegooNeptuneThumbnailPrusaMod\thumbnail.py", line 556, in <module>
  File "J:\work\programming\Python\ElegooNeptuneThumbnailPrusaMod\ElegooNeptuneThumbnailPrusaMod\thumbnail.py", line 432, in run
  File "J:\work\programming\Python\ElegooNeptuneThumbnailPrusaMod\ElegooNeptuneThumbnailPrusaMod\thumbnail.py", line 204, in prepare
  File "J:\work\programming\Python\ElegooNeptuneThumbnailPrusaMod\ElegooNeptuneThumbnailPrusaMod\thumbnail.py", line 35, in myround
ValueError: could not convert string to float: '12750.19, 0.00'
```

> It would be nice if you can re-produce the issue and show the line that causing the issue (find it in gcode by the number from error message).

Line 49196:
```
; EXECUTABLE_BLOCK_END

; filament used [mm] = 12750.19, 0.00
; filament used [cm3] = 30.67, 0.00
; filament used [g] = 38.95, 0.00
; filament cost = 38.95, 0.00
; total filament used [g] = 38.95
; total filament cost = 38.95
; total layers count = 134
; estimated printing time (normal mode) = 1h 12m 53s
```
[Test.zip](https://github.com/user-attachments/files/18536521/Test.zip)

**Comment by fifonik** [comment]
Thanks. I've just pushed updated version (.py for now). It would be nice if someone test it.

P.S. Planning to make a few more changes and build .exe on the next week.

**Comment by fifonik** [comment]
I've added some other things and released 2.1.0 (exe)
I hope the issue is fixed.

**Comment by Felix14-v2** [comment]
Just tested, the issue is completely fixed. Thanks you so much!
